### ISSUE TITLE
Newly added items have no thumbnail when extracted

### ISSUE THREAD

**Issue by TheOtterBear** [joonaspaakko/audible-library-extractor#150]
I just added some new audiobooks to my wish list and when I extracted it these items do show up but they have no thumbnails.  The entries have the little red icon that says the store page was possibly removed or it became unavailable in your region since it was added. They were just added a few minutes earlier and if you click on the title it will take you to the store page.  I tried extracting again but it didn't help.

I'm using Chrome.

**Comment by joonaspaakko** [comment]
I'll have to see for myself later, but if you didn't, try clicking the trashcan icon on the extraction settings -> [Wishlist 🗑️] and then extract again. If a book is already extracted, there are some data points that get left out after the first extraction to speed it up, so it's possible your second attempt couldn't have fixed it.

**Comment by TheOtterBear** [comment]
I tried that and lost most of the existing thumbnails as well.  It still pulled about 50 out of 500+.   Unfortunately, I read and acted on your reply from the email I received which did include the suggestion about exporting first.  So I have no way to get them back.

**Comment by joonaspaakko** [comment]
I was able to replicate the issue on my end. Because it's saying "missing", that means it wasn't able to extract the store page for the book, which is pretty concerning. A few books here and there I'd understand but not this many (I was able to get 75 wishlisted books out of 683). What concerns me the most is that clicking the book title in the gallery leads to the store page, so why did it fail to find it during the extraction. Unfortunately this is yet another bigger issue that can only be fixed with a new release and this is not the only big issue.

**Comment by TheOtterBear** [comment]
I may give that a try.  I could live with it as is until fixed but I do tend to rely on the covers to identify them quickly.  Thanks for looking into it and hopefully you can get it resolved for good.

**Comment by TheOtterBear** [comment]
An update: 
I tried the 0.2.11 draft and it throws an error message so I went back to 0.2.10.  The error was:
deifcolkciolkllaikijldnjeloeaall is blocked
This page has been blocked by Chrome
ERR_BLOCKED_BY_CLIENT

I added a few new books to my library and extracted it and it worked fine.  It downloaded everything, so it's just the wishlist part that is not working.  When the wishlist is set to grid mode it just shows blank blocks where the thumbnails would be overlaid by the title.  Clicking on them doesn't even expands the information box like it did before.  The only thing that functions is the sample play button.

In spreadsheet mode clicking on an item does expand the information panel but it only contains the title and the red "missing" tag, all other information is missing. Clicking on the title does take me to the store page and the sample play button does work.

**Comment by joonaspaakko** [comment]
Could you try v.0.2.11 again? I'm hoping it's a temporary thing thst had something to do with your internet connection maybe. 

If it still doesn't work, could you [try to use v.0.2.11 in incognito](https://support.google.com/chrome/a/answer/13130396?hl=en).

**Comment by TheOtterBear** [comment]
Sorry, v.0.2.11 gets the error incognito mode also.  I've even deleted all data, uninstalled the extension, restarted chrome, reinstalled it, and re-extracted the data.  All the library info extracted fine but the wishlist is still broken.  Same results as before.

**Comment by joonaspaakko** [comment]
Alright, I'm going to keep testing but so far I haven't been able to replicate this new blocked issue you're getting in the new version.

> And it's not giving you [this thing](https://github.com/joonaspaakko/audible-library-extractor/issues/110) after refreshing the Audible website after the extraction? This may happen if you're extracting a lot of data at once. If it 8s this one it might help to extract wishlist first.

**Comment by TheOtterBear** [comment]
No, I'm not getting that Audible message after extracting.  Hopefully there will be some kind of resolution in the future.

I do appreciate you checking it all out!

**Comment by joonaspaakko** [comment]
I'll keep looking. I may have to get back to you some time later (days or weeks later) with some test builds if I can't figure it out on my own.

**Comment by smrtsmrf** [comment]
+1 this. For my wishlist, also no thumbnails or details, just the sample play button. Also seeing the "missing" tag.

Interestingly, if I go to the spreadsheet view and click the audible icon (where I can see the "missing" message), it expands a details view (though nothing really is there. But then I go back to the grid view, now the details view is still open (and still mostly empty), and I can't close it. Clicking on the same book doesn't do it, and clicking on a different book doesn't do it either. Weird state.

**Comment by joonaspaakko** [comment]
@smrtsmrf, @TheOtterBear 

It's been ages, but the wishlist extraction and all the major bugs have been fixed, and it should work in any new Chromium versions. I'm still seeing an unusual amount of errors in the `chrome:extensions` error log, but it seems to function, not that I've tested every single feature yet (mainly CSV export and wallpaper creator).  

I figured that I'd let you know in case you want to try it before I do the release, which now that I'm back to work may easily take a week.

> **Draft installation instructions**
> 1. [Download the current v.0.2.11 draft](https://github.com/joonaspaakko/audible-library-extractor/raw/refs/heads/master/audible-library-extractor-0.2.11.zip).
> 2. Go to the address: `chrome:extensions` or: `Window > Extensions`.
> 3. Turn on the developer mode from the top right
> 4. Drag the downloaded .zip file in the browser window to install

**Comment by smrtsmrf** [comment]
Either the modified timestamp was it, or github pages was misbehaving. I added a new line to the top level files and it changed the tiemstamp to today, and then the github pages built fine. Not sure if my change had anything to do with it or if github just fixed itself. 🤷‍♀️

**Comment by joonaspaakko** [comment]
Hmmn... Might be worth looking into looking into, since I do live in the future compared to some countries (Finland). 

Then again I think if that were and issue, Chrome Web Store releases take about a day or two to be reviewed, so it might never really show up other than straight from Github. Github pages is known to be a bit sporadic sometimes so who knows.

**Comment by smrtsmrf** [comment]
@joonaspaakko I have been able to reproduce again, ruling out a problem with Github pages. Each time I download the files, the files modified date attribute is in the future. And when uploading those to Github pages, for whatever reason, it doesn't pick up those changes. 

If I manually tweak the files to set the modified date properly, Github pages builds just fine.

I did not have this problem previous to this draft release.

**Comment by joonaspaakko** [comment]
@smrtsmrf, how long did you wait after the build succeed? I'm pretty sure I've once waited 15 minutes for the built site to actually be online, so maybe there's a chance it's that? 

I would like to know if it loads the page and has errors or if it loads some kind of github "There's nothing here" page instead.

Didn't think to try yet, but I guess could try changing the modification date and into the future and see if it fails for me.

> Overall I'm still quite skeptical about it being this particular about modification dates.

**Comment by smrtsmrf** [comment]
I waited about 10 minutes or so. Once I changed the modification dates, as soon as the Gitlab action said the build was done, the new changes were there immediately. So it doesn't seem to be an issue with a time delay.

I tried the trick of disabling Github pages and re-enabling, so it will kick off another build. Same result though - it doesn't pick up the new changes with modification dates in the future.

I didn't get any visible errors anywhere (though I didn't check the dev console). The page loaded fine, just with outdated data. (For example: I was updating because I had created a new collection. The collection was not visible until I fixed the modification dates and rebuilt.)

**Comment by joonaspaakko** [comment]
I wasn't able to recreate the issue.

Given that for you the page loaded, just with the old data, I would presume there wouldn't be any errors to care about, but it does make me lean towards some kind of browser cache issue. 

If this happens again, could you try [clearing cache and refreshing the page](https://help.codehs.com/en/articles/4951972-how-to-clear-your-browser-cache-and-hard-refresh#h_dfff8ab987).
